name: CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - uses: actions/checkout@v2
    - name: Download zip
      run:  sudo apt-get install zip
      
    - name: Zip addon
      run:  zip -r data_vis.zip data_vis
