name: CI
on:
  push:
    branches: 
    - master
    - develop
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./data_vis.zip . -i ./data_vis
 
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
